---
global:
  loglevel: 'debug'
  logfile: 'app.log'
  logfile_errors: 'error.log'
  username: 'deployer'
  password: 'Deploy1T'
  bind: '127.0.0.1'
  port: '8088'
vcs:
  puppet-control:
    _all:
      command: 'echo _all'
    production:
      #command: 'r10k deploy environment <%= branch_name %> -pv'
      command: 'echo production <%= branch_name %>'
    development:
      command: 'echo development'
  encdata:
    master:
      command: 'git pull'
  puppet-*:
    _all:
      command: 'echo all puppet-*'

